---
title: "Stat 850 Project Proposal- Tornado Data Alayzing"
format: html
editor: visual
---

## Introduction

A tornado is a rapidly rotating column of air that extends from a thunderstorm to the ground, forming a funnel-shaped cloud, known as a tornado vortex ([Tornadoes.(n.d.)](https://www.nssl.noaa.gov/research/tornadoes/)). These violent windstorms are characterized by their destructive power, often causing severe damage to structures, vehicles, and natural environments. So this most destructive and fascinating natural phenomena that occur in the United States, with the power to wreak havoc on communities, devastate landscapes, and claim lives. They are often referred to as nature's most violent storms due to their ferocity and unpredictability. In the USA, tornadoes have long been a subject of both fear and awe, prompting researchers, meteorologists, and emergency response teams to seek a deeper understanding of these formidable weather events.

The interest in exploring this extensive tornado data set arises from the profound impact that tornadoes have on American society and the natural environment. Tornadoes are a recurring and unpredictable threat, causing significant economic losses and, more importantly, putting human lives at risk. As a researcher, I am driven by the need to better understand the behavior and patterns of tornadoes to mitigate their destructive potential and improve our ability to predict and respond to them.

The opportunity to delve into a comprehensive data set, spanning more than seven decades, is both exciting and promising. It allows for a deep exploration of trends, anomalies, and potential patterns in tornado occurrence and behavior, which can inform disaster preparedness, risk assessment, and policy development.

## Data

### Source

The data source for the project is comes from - [TidyTuesday Archive](https://github.com/rfordatascience/tidytuesday) data project, and the data set used is the [Tornado Data](https://www.spc.noaa.gov/wcm/data/1950-2022_actual_tornadoes.csv).

```{r, echo = F,message = F, warning = F}

library(tidyverse)

#read the data

tornado <-read.csv("https://www.spc.noaa.gov/wcm/data/1950-2022_actual_tornadoes.csv")

#print the data information
str(tornado)

```

### Description

This data set provides comprehensive information about tornadoes, including various attributes such as tornado numbers, years, months, days, dates, times, geographical coordinates, magnitudes, injuries, fatalities, property losses, and more. The data offers insights into the characteristics and impacts of tornadoes that have occurred from 1950 to 2022.

It is sourced from NOAA's National Weather Service Storm Prediction Center Severe Weather Maps, Graphics, and Data Page ([Storm Prediction](https://www.spc.noaa.gov/wcm/)).This offers a rich resource for the analysis and study of tornado occurrences and their impacts, enabling researchers and meteorologists to gain insights into the patterns and characteristics of tornadoes spanning over seven decades.

Here is a data dictionary showing each variable, the type of variable, units, and range of values that are possible:

+------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| Name                                     | Description                                                                                                                                                                                                  | Type        | Units      | Range/Values                                                                                                                                              |       |
+------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| Tornado Number (om)                      | An identifier for each tornado within a specific year                                                                                                                                                        | Integer     |            |                                                                                                                                                           |       |
+------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| Year (yr)                                | The year in which the tornado occurred                                                                                                                                                                       | Integer     |            | 1950 - 2022                                                                                                                                               |       |
+------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| Month (mo)                               | The month of the tornado occurrence                                                                                                                                                                          | Integer     |            | 1 to 12                                                                                                                                                   |       |
+------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| Day of the Month (dy)                    | The specific day of the month when the tornado struck                                                                                                                                                        | Integer     |            | 1 to 31                                                                                                                                                   |       |
+------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| Date                                     | The date of the tornado occurrence                                                                                                                                                                           | categorical | MMDYYYY    |                                                                                                                                                           |       |
+------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| Time                                     | The time of day when the tornado was reported                                                                                                                                                                | categorical | HHMMSS     |                                                                                                                                                           |       |
+------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| Timezone (tz)                            | The timezone, using the [canonical tz database](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)                                                                                                | Integer     |            |                                                                                                                                                           |       |
+------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| State (st)                               | Affected State                                                                                                                                                                                               | categorical |            | A two-letter postal abbreviation representing the affected state. (DC=Washington,DC;PR=Puerto Rico,VI=Virgin Islands)                                     |       |
+------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| State FIPS Number (stf)                  | The State FIPS (Federal Information Processing Standards) number.                                                                                                                                            | Integer     |            |                                                                                                                                                           |       |
+------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| Magnitude (mag)                          | The magnitude of the tornado, recorded on the [F scale](https://www.spc.noaa.gov/faq/tornado/f-scale.html). [EF scale](https://www.weather.gov/tae/ef_scale) from 2007. Some are estimated                   | Integer     |            |                                                                                                                                                           |       |
+------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| Injuries (inj)                           | The number of injuries associated with the tornado                                                                                                                                                           | Integer     |            |                                                                                                                                                           |       |
+------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| Fatalities (fat)                         | The number of fatalities caused by the tornado                                                                                                                                                               | Integer     |            |                                                                                                                                                           |       |
+------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| Loss (loss)                              | Estimated property loss information, with values grouped into ranges for years before 1996                                                                                                                   | numeric     | In dollars | Prior to 1996, values were grouped into ranges. The reported number for such years is the maximum of its range                                            |       |
+------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| Starting Latitude (slat)                 | The geographical coordinates of the tornado's starting point. (Starting latitude )                                                                                                                           | numeric     | Degrees    |                                                                                                                                                           |       |
+------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| Starting Longitude (slon)                | The geographical coordinates of the tornado's starting point. (Starting longitude)                                                                                                                           | numeric     | Degrees    |                                                                                                                                                           |       |
+------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| Ending Latitude (elat)                   | The geographical coordinates of the tornado's endpoint. (Ending latitude)                                                                                                                                    | numeric     | Degrees    |                                                                                                                                                           |       |
+------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| Ending Longitude (elon)                  | The geographical coordinates of the tornado's endpoint. (Ending longitude)                                                                                                                                   | numeric     | Degrees    |                                                                                                                                                           |       |
+------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| Length (len)                             | The length of the tornado's path                                                                                                                                                                             | numeric     | In miles   |                                                                                                                                                           |       |
+------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| Width (wid)                              | The width of the tornado's path                                                                                                                                                                              | Integer     | In yards   |                                                                                                                                                           |       |
+------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| Number of States Affected (ns)           | The number of states impacted by the tornado                                                                                                                                                                 | Integer     |            | ```                                                                                                                                                       |       |
|                                          |                                                                                                                                                                                                              |             |            |  1, 2, or 3..                                                                                                                                             |       |
|                                          |                                                                                                                                                                                                              |             |            | ```                                                                                                                                                       |       |
+------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| State Number (sn)                        | The state no of the row                                                                                                                                                                                      | Integer     |            | Indicates whether the row contains the entire track information for a state (1) or if there is at least one more entry for the state for that tornado (0) |       |
+------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| FIPS Codes for Counties (f1, f2, f3, f4) | [FIPS codes](https://transition.fcc.gov/oet/info/maps/census/fips/fips.txt#:~:text=FIPS%20codes%20are%20numbers%20which,to%20which%20the%20county%20belongs) for up to four counties affected by the tornado | Integer     |            |                                                                                                                                                           |       |
+------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| Was the Magnitude Estimated (fc)         | A logical variable indicating whether the magnitude value was estimated                                                                                                                                      | Integer     |            | ```                                                                                                                                                       |       |
|                                          |                                                                                                                                                                                                              |             |            |  1 or 0                                                                                                                                                   |       |
|                                          |                                                                                                                                                                                                              |             |            | ```                                                                                                                                                       |       |
+------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+-------+

## Project Goals

The [Tornado Data](https://www.spc.noaa.gov/wcm/data/1950-2022_actual_tornadoes.csv) set from NOAA, covering the years 1950 to 2022, is fascinating because it holds the potential to reveal valuable insights.

The goals of this project are to utilize this data to explore and analyze several key aspects related to tornado occurrences in the United States. Here are the specific goals and the intriguing subjects we hope to investigate.

**Data Cleaning and Pre-processing**

-   Conduct data cleaning to handle missing values, outliers, and inconsistencies in the tornado data set, ensuring that the data is of high quality for analysis.

-   Standardize and transform data types as needed to make the data set suitable for statistical analysis.

-   Data Pre-processing with standardize data types and formats to ensure consistency.

**Tornado Trends and Patterns**

-   Examine long-term trends in tornado frequency and intensity, and identify any significant changes over the decades. Are tornadoes becoming more frequent or intense over time.

-   Investigate seasonal and regional variations in tornado occurrences. Are there particular months or states with higher tornado activity.

-   Investigate the distribution of tornado magnitudes and their classifications.

**Tornado Impact Assessment**

-   Assess the economic and human impact of tornadoes by analyzing variables such as injuries, fatalities, property and crop losses.

-   Explore the spatial distribution of tornado impact, focusing on the geographical areas most affected by these natural disasters.

**Developing Shiny Application**

-   The Shiny application will be built to import and utilize the tornado data set.

### Data Analyzing Approach

1.  Identifying and addressing missing values in the tornado data set. This will involve techniques such as imputation or removal of rows with significant missing data. Special attention will be given to critical columns, such as **inj**, **fat**, and **mag**. And perform outlier detection to identify data points that significantly deviate from the norm

2.  Data inconsistencies, such as conflicting records or contradictory information, will be resolved. This may involve cross-referencing with external sources particularly in FIPS Codes for Counties (**f1**, **f2**, **f3**, **f4**).

3.  Additional features or variables may be created to enhance the analysis. For example, calculate the total impact (injuries, fatalities, loss) for each tornado event, create time-based variables (season, time of day).

4.  To examine long-term trends in tornado frequency and intensity, we can perform a time series analysis of tornado occurrences over the years, studying variations in the number and intensity of tornadoes.

5.  For investigating seasonal and regional variations in tornado occurrences, we can create visualizations and summaries that highlight the months and states with the highest tornado activity, using the **mo**, **st**, and **stf** columns.

6.  To investigate the distribution of tornado magnitudes, we can create histograms and box plots of the **mag** column, which represents tornado intensity. We can also examine changes in tornado magnitude over time.

7.  To assess the economic and human impact of tornadoes, we can calculate statistics such as the mean, median, and maximum values of injuries, fatalities, property losses, and crop losses. This will help identify trends and the most severely affected areas.

8.  Analyzing the geographical distribution of tornado impact can be done by mapping the areas with the highest impacts and visualizing the affected regions.

9.  With the data analysis approach mentioned earlier, we are planing to add those in to a Shiny web application with implementing a variety of interactive visualizations within the Shiny application to address each of the project's goals more effectively. For instance:

-   Time series plots for trend analysis.
-   Heatmaps, choropleth maps, or scatter plots to visualize regional and seasonal variations.
-   Box plots, histograms, and distribution curves for magnitude and impact analysis.
-   Interactive maps for visualizing tornado impact locations.

## Division of Labor

+-------------------------------------------+----------------+-------------------------+
| Steps                                     | Members        | Deadline                |
+===========================================+================+=========================+
| Proposal Document                         | Chathurika, Li | Week 1-Due 10/30/2023   |
+-------------------------------------------+----------------+-------------------------+
| Data Cleaning and Pre-processing          | Li             | Week 1                  |
+-------------------------------------------+----------------+-------------------------+
| Additional features or variables creating | Chathurika     | Week 1,2                |
+-------------------------------------------+----------------+-------------------------+
| Identify Tornado Trends and Patterns      | Li             | Week 2                  |
+-------------------------------------------+----------------+-------------------------+
| Tornado Impact Assessment                 | Chathurika     | Week 2                  |
+-------------------------------------------+----------------+-------------------------+
| Developing Shiny Application              | Chathurika     | Week 4                  |
+-------------------------------------------+----------------+-------------------------+
| Project Presentation                      | Chathurika, Li | Week 5-Due 12/04/2023   |
+-------------------------------------------+----------------+-------------------------+
| Project Report                            | Chathurika, Li | Week 5,6-Due 12/08/2023 |
+-------------------------------------------+----------------+-------------------------+

## References

Tornadoes. (n.d.). NOAA National Severe Storms Laboratory. https://www.nssl.noaa.gov/research/tornadoes/ In-Text Citation: (Tornadoes, n.d.)

Storm Prediction Center Maps, Graphics, and Data Page. (n.d.). https://www.spc.noaa.gov/wcm/ In-Text Citation: (Storm Prediction Center Maps, Graphics, and Data Page, n.d.)


------

project-tornado-chasers-1$ git fame . --incl=".(q|Q|r|R)md"
Processing: 100%|██████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 337.16file/s]
Total commits: 22
Total ctimes: 49
Total files: 5
Total loc: 412
| Author                      |   loc |   coms |   fils |  distribution   |
|:----------------------------|------:|-------:|-------:|:----------------|
| github-classroom[bot]       |   264 |      1 |      4 | 64.1/ 4.5/80.0  |
| Mona LisaChathurikaHarshani |   148 |     12 |      1 | 35.9/54.5/20.0  |
| Li Song                     |     0 |      9 |      0 | 0.0/40.9/ 0.0   |

I suggest Chathurika change her name to be Chathurika Harshani instead of Mona Lisa ChathurikaHarshani, but I'm not going to judge :)


Side note: I <3 this dataset so much. I hope you have lots of fun with it.
